const data = [
  {
    id: 5606,
    dealerCode: 7000320,
    stockAge: 1115,
    vin: "WP0AA2984KS261984",
    lockForOrderId: null,
    inventoryNumber: "A65255",
    stockStatus: "IN_STOCK",
    salesStatus: "AVAILABLE",
    vehicleType: "USED_CAR",
    vehicleOrigin: "TRADE_IN_FOR_USED_CAR",
    firstRegistrationDate: 1561305600,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: false,
    porscheApproved: true,
    modelName: "718 Cayman",
    modelCode: "982120",
    modelYear: 2019,
    exteriorColorHexCode: "#dc3513",
    exteriorColorTagHexCode: "#F47920",
    exteriorColorName: "熔岩橙",
    interiorName: "黑色标准内饰",
    interiorDescription:
      "侧垫、座椅头枕、座椅中心、方向盘轮圈、门把手嵌件以及换档杆均为黑色真皮。<br>",
    interiorColorCockpitHexCode: "#000000",
    interiorColorCockpitStitchingCode: "#000000",
    interiorColorSeatColorHexCode: "#000000",
    interiorColorSeatStitchingColorHexCode: "#000000",
    interiorColorTagHexCode: "#000000",
    priceHistory: [
      {
        value: 628000,
        currency: null,
        date: 1604687437,
      },
    ],
    priceValue: 628000,
    mileageValue: 12376,
  },
  {
    id: 6998,
    dealerCode: 7000320,
    stockAge: 1114,
    vin: "WP1AA2954HLB00168",
    lockForOrderId: 535,
    inventoryNumber: "351160",
    stockStatus: "IN_STOCK",
    salesStatus: "AVAILABLE",
    vehicleType: "USED_CAR",
    vehicleOrigin: "TRADE_IN_FOR_USED_CAR",
    firstRegistrationDate: 1459440000,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: false,
    porscheApproved: false,
    modelName: "Macan",
    modelCode: "95BAA1",
    modelYear: 2017,
    exteriorColorHexCode: "#3f2021",
    exteriorColorTagHexCode: "#85604e",
    exteriorColorName: "桃红木金属漆",
    interiorName: "黑色标配内饰",
    interiorDescription:
      "黑色标配内饰。与内饰同色光面真皮：方向盘轮圈、选档杆和防尘罩；座椅座套：Alcantara面料/人造革。说明：与舒适性记忆功能组件 (14 向) 或是带舒适性记忆功能组件的自适应运动型座椅 (18 向) 一起装配时，座椅采用光面真皮座套。",
    interiorColorCockpitHexCode: "#000000",
    interiorColorCockpitStitchingCode: "#000000",
    interiorColorSeatColorHexCode: "#000000",
    interiorColorSeatStitchingColorHexCode: "#000000",
    interiorColorTagHexCode: "#000000",
    priceHistory: [
      {
        value: 384000,
        currency: null,
        date: 1606777548,
      },
    ],
    priceValue: 384000,
    mileageValue: 125000,
  },
  {
    id: 4043,
    dealerCode: 7000320,
    stockAge: 1114,
    vin: "WP1AA29Y7KDA26692",
    lockForOrderId: null,
    inventoryNumber: "A38284",
    stockStatus: "IN_STOCK",
    salesStatus: "AVAILABLE",
    vehicleType: "USED_CAR",
    vehicleOrigin: "PURCHASE_FROM_COMMERCIAL_OWNER",
    firstRegistrationDate: 1571155200,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: false,
    porscheApproved: true,
    modelName: "Cayenne",
    modelCode: "9YAAA1",
    modelYear: 2019,
    exteriorColorHexCode: "#212721",
    exteriorColorTagHexCode: "#000000",
    exteriorColorName: "黑玉色金属漆",
    interiorName: "黑色部分真皮内饰",
    interiorDescription:
      "标准颜色内饰，部分采用真皮材质。下列部件采用与内饰同色的压花真皮：前后排座椅中心、前后排座椅内侧垫、前后排座椅头枕中心、前后门板扶手和门把手、前排中控台扶手和折叠式后排扶手。光面真皮方向盘轮圈和选档杆<br>",
    interiorColorCockpitHexCode: "#000000",
    interiorColorCockpitStitchingCode: "#000000",
    interiorColorSeatColorHexCode: "#000000",
    interiorColorSeatStitchingColorHexCode: "#000000",
    interiorColorTagHexCode: "#000000",
    priceHistory: [
      {
        value: 978000,
        currency: null,
        date: 1604692227,
      },
    ],
    priceValue: 978000,
    mileageValue: 13000,
  },
  {
    id: 5484,
    dealerCode: 7000320,
    stockAge: 1113,
    vin: "WP0AA2983KS260664",
    lockForOrderId: null,
    inventoryNumber: "A21740",
    stockStatus: "IN_STOCK",
    salesStatus: "AVAILABLE",
    vehicleType: "USED_CAR",
    vehicleOrigin: "TRADE_IN_FOR_USED_CAR",
    firstRegistrationDate: 1545062400,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: false,
    porscheApproved: false,
    modelName: "718 Cayman",
    modelCode: "982120",
    modelYear: 2019,
    exteriorColorHexCode: "#ba0c2f",
    exteriorColorTagHexCode: "#fb1a08",
    exteriorColorName: "卫红",
    interiorName: "黑色标准内饰",
    interiorDescription:
      "侧垫、座椅头枕、座椅中心、方向盘轮圈、门把手嵌件以及换档杆均为黑色真皮。<br>",
    interiorColorCockpitHexCode: "#000000",
    interiorColorCockpitStitchingCode: "#000000",
    interiorColorSeatColorHexCode: "#000000",
    interiorColorSeatStitchingColorHexCode: "#000000",
    interiorColorTagHexCode: "#000000",
    priceHistory: [
      {
        value: 598000,
        currency: null,
        date: 1605392129,
      },
    ],
    priceValue: 598000,
    mileageValue: 10600,
  },
  {
    id: 6997,
    dealerCode: 7000320,
    stockAge: 1111,
    vin: "WP0AA2975FL007112",
    lockForOrderId: null,
    inventoryNumber: "310578",
    stockStatus: "IN_STOCK",
    salesStatus: "AVAILABLE",
    vehicleType: "USED_CAR",
    vehicleOrigin: "TRADE_IN_FOR_USED_CAR",
    firstRegistrationDate: 1448553600,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: false,
    porscheApproved: false,
    modelName: "Panamera",
    modelCode: "970110",
    modelYear: 2015,
    exteriorColorHexCode: "#3f2021",
    exteriorColorTagHexCode: "#85604e",
    exteriorColorName: "桃红木金属漆",
    interiorName: "马莎拉真皮内饰",
    interiorDescription:
      "马莎拉光面真皮内饰，标准真皮饰件的全部内容，加上仪表板上部和前部 (包括组合仪表护盖)。仪表板下部 (包括手套箱盖)、中控台下部、方向盘安全气囊模组、前/后车门饰板上部、C 柱 (下部)、前/后车门饰板中心嵌件、前/后车门饰板下部、后部烟灰缸、前车门储物箱盖、真皮座椅 (包括真皮前/后座椅外侧垫、前/后座椅头枕外侧垫、前排座椅靠背外壳以及带储物箱的后排下部可折叠扶手)。",
    interiorColorCockpitHexCode: "#4d3837",
    interiorColorCockpitStitchingCode: "#4d3837",
    interiorColorSeatColorHexCode: "#4d3837",
    interiorColorSeatStitchingColorHexCode: "#4d3837",
    interiorColorTagHexCode: "#782f2f",
    priceHistory: [
      {
        value: 699000,
        currency: null,
        date: 1605641433,
      },
    ],
    priceValue: 699000,
    mileageValue: 88800,
  },
  {
    id: 5609,
    dealerCode: 7000320,
    stockAge: 1111,
    vin: "WP0CA298XJS210318",
    lockForOrderId: null,
    inventoryNumber: "456805",
    stockStatus: "IN_STOCK",
    salesStatus: "AVAILABLE",
    vehicleType: "USED_CAR",
    vehicleOrigin: "TRADE_IN_FOR_USED_CAR",
    firstRegistrationDate: 1508083200,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: false,
    porscheApproved: false,
    modelName: "718 Boxster",
    modelCode: "982320",
    modelYear: 2018,
    exteriorColorHexCode: "#dce0dc",
    exteriorColorTagHexCode: "#efefef",
    exteriorColorName: "白色",
    interiorName: "波尔多红真皮内饰",
    interiorDescription:
      "标配内饰，外加以下采用真皮的部件：包含仪表组护盖的仪表板上部、方向盘安全气囊模组、包含手套箱盖的仪表板下部、门板上部、车门中心面板、中控台侧面、后排侧围板、座椅基座、前排座椅靠背背面 (不搭配订购号 P01、P03、P05、P07 的部件)、后排座椅中心、后排座垫、后排传动轴通道。所有真皮部件 (包括标配部件) 均为光面真皮。车门板饰条采用镀银。另外 A 柱和 B 柱表面采用 Alcantara 面料。911 Carrera Cabriolet 车型：A 柱饰板和挡风玻璃通风饰板镶边额外采用光面真皮",
    interiorColorCockpitHexCode: "#782f2f",
    interiorColorCockpitStitchingCode: "#782f2f",
    interiorColorSeatColorHexCode: "#782f2f",
    interiorColorSeatStitchingColorHexCode: "#782f2f",
    interiorColorTagHexCode: "#782f2f",
    priceHistory: [
      {
        value: 628000,
        currency: null,
        date: 1605288933,
      },
    ],
    priceValue: 628000,
    mileageValue: 19165,
  },
  {
    id: 4711,
    dealerCode: 7000320,
    stockAge: 1109,
    vin: "WP1AA2954KLB17463",
    lockForOrderId: null,
    inventoryNumber: "A42935",
    stockStatus: "IN_STOCK",
    salesStatus: "AVAILABLE",
    vehicleType: "USED_CAR",
    vehicleOrigin: "TRADE_IN_FOR_USED_CAR",
    firstRegistrationDate: 1567612800,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: false,
    porscheApproved: false,
    modelName: "Macan",
    modelCode: "95BAG1",
    modelYear: 2019,
    exteriorColorHexCode: "#3f2021",
    exteriorColorTagHexCode: "#85604e",
    exteriorColorName: "桃红木金属漆",
    interiorName: "黑色和石榴红真皮组件，搭配部分真皮座椅",
    interiorDescription:
      "搭配双色调组合时，下列真皮部件采用浅色：中控台储物箱盖、座椅中心、前后排座椅内垫、座椅头枕正面、前后门板扶手和车门拉手<br>",
    interiorColorCockpitHexCode: "#000000",
    interiorColorCockpitStitchingCode: "#993333",
    interiorColorSeatColorHexCode: "#993333",
    interiorColorSeatStitchingColorHexCode: "#993333",
    interiorColorTagHexCode: "#782f2f",
    priceHistory: [
      {
        value: 618000,
        currency: null,
        date: 1605142655,
      },
    ],
    priceValue: 618000,
    mileageValue: 7520,
  },
  {
    id: 7047,
    dealerCode: 7000320,
    stockAge: 1109,
    vin: "WP0BJ2971LL163468",
    lockForOrderId: null,
    inventoryNumber: "B23782",
    stockStatus: "IN_STOCK",
    salesStatus: "AVAILABLE",
    vehicleType: "USED_CAR",
    vehicleOrigin: "TRADE_IN_FOR_USED_CAR",
    firstRegistrationDate: 1578326400,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: false,
    porscheApproved: true,
    modelName: "Panamera 4 Executive",
    modelCode: "97BBY1",
    modelYear: 2020,
    exteriorColorHexCode: "#d9d9d6",
    exteriorColorTagHexCode: "#efefef",
    exteriorColorName: "细花白金属漆",
    interiorName: "黑色/波尔多红双色调光面真皮内饰",
    interiorDescription:
      "<p>组件与标准颜色真皮内饰组件相同，但装饰条采用对比色。<br></p><p>说明：<br>- 仪表板上部和地毯采用深色<br>- 仪表板上部和前后车门饰件上部的装饰缝线采用浅色 <br>- 车顶衬里采用对应浅色，搭配黑色和哑灰色、马莎拉红和乳白色、马鞍棕和卢克索米色、黑色和卢克索米色 <br>- 车顶衬里采用深色，搭配黑色和波尔多红或黑色和马鞍棕</p><br><br>",
    interiorColorCockpitHexCode: "#000000",
    interiorColorCockpitStitchingCode: "#782F2F",
    interiorColorSeatColorHexCode: "#782F2F",
    interiorColorSeatStitchingColorHexCode: "#782F2F",
    interiorColorTagHexCode: "#782f2f",
    priceHistory: [
      {
        value: 1480000,
        currency: null,
        date: 1605046597,
      },
    ],
    priceValue: 1480000,
    mileageValue: 7066,
  },
  {
    id: 4044,
    dealerCode: 7000320,
    stockAge: 1109,
    vin: "WP1AA2952FLB17757",
    lockForOrderId: null,
    inventoryNumber: "288584",
    stockStatus: "IN_STOCK",
    salesStatus: "AVAILABLE",
    vehicleType: "USED_CAR",
    vehicleOrigin: "PURCHASE_FROM_PRIVATE_OWNER",
    firstRegistrationDate: 1426608000,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: false,
    porscheApproved: false,
    modelName: "Macan",
    modelCode: "95BAA1",
    modelYear: 2015,
    exteriorColorHexCode: "#3f2021",
    exteriorColorTagHexCode: "#85604e",
    exteriorColorName: "桃红木金属漆",
    interiorName: "标配黑色内饰",
    interiorDescription:
      "标配黑色内饰。与内饰同色的光面真皮：方向盘轮圈、选档杆和护罩；座椅蒙面：Alcantara 面料/人造革。注释：搭配舒适性记忆功能组件 (14 向) 或带舒适性记忆功能组件 (18 向) 的自适应运动型座椅，座椅饰以光面真皮",
    interiorColorCockpitHexCode: "#000000",
    interiorColorCockpitStitchingCode: "#000000",
    interiorColorSeatColorHexCode: "#000000",
    interiorColorSeatStitchingColorHexCode: "#000000",
    interiorColorTagHexCode: "#000000",
    priceHistory: [
      {
        value: 398000,
        currency: null,
        date: 1605199032,
      },
    ],
    priceValue: 398000,
    mileageValue: 57000,
  },
  {
    id: 4045,
    dealerCode: 7000320,
    stockAge: 1109,
    vin: "WP1AA2954KLB09654",
    lockForOrderId: null,
    inventoryNumber: "A29151",
    stockStatus: "IN_STOCK",
    salesStatus: "AVAILABLE",
    vehicleType: "USED_CAR",
    vehicleOrigin: "PURCHASE_FROM_PRIVATE_OWNER",
    firstRegistrationDate: 1571846400,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: false,
    porscheApproved: true,
    modelName: "Macan",
    modelCode: "95BAG1",
    modelYear: 2019,
    exteriorColorHexCode: "#3f2021",
    exteriorColorTagHexCode: "#85604e",
    exteriorColorName: "桃红木金属漆",
    interiorName: "黑色标准内饰",
    interiorDescription:
      "方向盘轮圈、选档杆和防尘罩采用黑色光面真皮；座椅采用\r\n  Alcantara® 面料/人造革",
    interiorColorCockpitHexCode: "#000000",
    interiorColorCockpitStitchingCode: "#000000",
    interiorColorSeatColorHexCode: "#000000",
    interiorColorSeatStitchingColorHexCode: "#000000",
    interiorColorTagHexCode: "#000000",
    priceHistory: [
      {
        value: 582000,
        currency: null,
        date: 1605046611,
      },
    ],
    priceValue: 582000,
    mileageValue: 13000,
  },
  {
    id: 4706,
    dealerCode: 7000320,
    stockAge: 1109,
    vin: "WP0CA2984JS212419",
    lockForOrderId: null,
    inventoryNumber: "527587",
    stockStatus: "IN_STOCK",
    salesStatus: "AVAILABLE",
    vehicleType: "USED_CAR",
    vehicleOrigin: "TRADE_IN_FOR_USED_CAR",
    firstRegistrationDate: 1539792000,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: false,
    porscheApproved: false,
    modelName: "718 Boxster",
    modelCode: "982320",
    modelYear: 2018,
    exteriorColorHexCode: "#9d2235",
    exteriorColorTagHexCode: "#fb1a08",
    exteriorColorName: "胭脂红",
    interiorName: "标配内饰 / 黑色真皮运动型座椅升级版或运动型桶型座椅",
    interiorDescription: "标配内饰 / 黑色真皮运动型座椅升级版或运动型桶型座椅",
    interiorColorCockpitHexCode: "#000000",
    interiorColorCockpitStitchingCode: "#000000",
    interiorColorSeatColorHexCode: "#000000",
    interiorColorSeatStitchingColorHexCode: "#000000",
    interiorColorTagHexCode: "#000000",
    priceHistory: [
      {
        value: 668000,
        currency: null,
        date: 1605118344,
      },
    ],
    priceValue: 668000,
    mileageValue: 19898,
  },
  {
    id: 4707,
    dealerCode: 7000320,
    stockAge: 1109,
    vin: "WP1AA29Y1LDA05435",
    lockForOrderId: null,
    inventoryNumber: "B22448",
    stockStatus: "IN_STOCK",
    salesStatus: "AVAILABLE",
    vehicleType: "USED_CAR",
    vehicleOrigin: "TRADE_IN_FOR_USED_CAR",
    firstRegistrationDate: 1585238400,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: false,
    porscheApproved: true,
    modelName: "Cayenne",
    modelCode: "9YAAA1",
    modelYear: 2020,
    exteriorColorHexCode: "#d9d9d6",
    exteriorColorTagHexCode: "#efefef",
    exteriorColorName: "细花白金属漆",
    interiorName: "黑色内饰，部分真皮",
    interiorDescription:
      "下列部件采用与内饰同色的压花真皮：前后排座椅中心、前后排座椅侧垫、前后排座椅头枕中心、前后车门板扶手和门把手、前排中控台扶手和后排折叠扶手。光面真皮方向盘轮圈和选档杆。<br><br><br>",
    interiorColorCockpitHexCode: "#000000",
    interiorColorCockpitStitchingCode: "#000000",
    interiorColorSeatColorHexCode: "#000000",
    interiorColorSeatStitchingColorHexCode: "#000000",
    interiorColorTagHexCode: "#000000",
    priceHistory: [
      {
        value: 1068000,
        currency: null,
        date: 1605130958,
      },
    ],
    priceValue: 1068000,
    mileageValue: 20123,
  },
  {
    id: 4708,
    dealerCode: 7000320,
    stockAge: 1109,
    vin: "WP1AA2954KLB09749",
    lockForOrderId: null,
    inventoryNumber: "A29405",
    stockStatus: "IN_STOCK",
    salesStatus: "AVAILABLE",
    vehicleType: "USED_CAR",
    vehicleOrigin: "TRADE_IN_FOR_USED_CAR",
    firstRegistrationDate: 1566748800,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: false,
    porscheApproved: false,
    modelName: "Macan",
    modelCode: "95BAG1",
    modelYear: 2019,
    exteriorColorHexCode: "#474647",
    exteriorColorTagHexCode: "#757575",
    exteriorColorName: "火山灰金属漆",
    interiorName: "黑色标准内饰",
    interiorDescription:
      "方向盘轮圈、选档杆和防尘罩采用黑色光面真皮；座椅采用\r\n  Alcantara® 面料/人造革",
    interiorColorCockpitHexCode: "#000000",
    interiorColorCockpitStitchingCode: "#000000",
    interiorColorSeatColorHexCode: "#000000",
    interiorColorSeatStitchingColorHexCode: "#000000",
    interiorColorTagHexCode: "#000000",
    priceHistory: [
      {
        value: 618000,
        currency: null,
        date: 1605130937,
      },
    ],
    priceValue: 618000,
    mileageValue: 9037,
  },
  {
    id: 4709,
    dealerCode: 7000320,
    stockAge: 1109,
    vin: "WP0CA2980LS211951",
    lockForOrderId: null,
    inventoryNumber: "B48684",
    stockStatus: "IN_STOCK",
    salesStatus: "AVAILABLE",
    vehicleType: "USED_CAR",
    vehicleOrigin: "TRADE_IN_FOR_USED_CAR",
    firstRegistrationDate: 1587398400,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: false,
    porscheApproved: false,
    modelName: "718 Boxster T",
    modelCode: "982350",
    modelYear: 2020,
    exteriorColorHexCode: "#d9d9d6",
    exteriorColorTagHexCode: "#efefef",
    exteriorColorName: "细花白金属漆",
    interiorName: "黑色标准内饰",
    interiorDescription:
      "<p>侧垫、座椅头枕、座椅中心、方向盘轮圈、门把手镶嵌饰件以及换档杆均为黑色真皮<br><br></p>",
    interiorColorCockpitHexCode: "#000000",
    interiorColorCockpitStitchingCode: "#000000",
    interiorColorSeatColorHexCode: "#000000",
    interiorColorSeatStitchingColorHexCode: "#000000",
    interiorColorTagHexCode: "#000000",
    priceHistory: [
      {
        value: 768000,
        currency: null,
        date: 1605133045,
      },
    ],
    priceValue: 768000,
    mileageValue: 6258,
  },
  {
    id: 4710,
    dealerCode: 7000320,
    stockAge: 1109,
    vin: "WP0AJ2978KL104184",
    lockForOrderId: null,
    inventoryNumber: "A47003",
    stockStatus: "IN_STOCK",
    salesStatus: "AVAILABLE",
    vehicleType: "USED_CAR",
    vehicleOrigin: "TRADE_IN_FOR_USED_CAR",
    firstRegistrationDate: 1556467200,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: false,
    porscheApproved: false,
    modelName: "Panamera",
    modelCode: "97AAY1",
    modelYear: 2019,
    exteriorColorHexCode: "#474647",
    exteriorColorTagHexCode: "#757575",
    exteriorColorName: "火山灰金属漆",
    interiorName: "马莎拉红光面真皮内饰组件",
    interiorDescription:
      "马莎拉红真皮内饰组件 (所有真皮部件均采用光面真皮)：所有标准真皮部件均采用标准颜色光面真皮。此外以下部件也采用标准颜色光面真皮：包括真皮座椅外侧侧垫在内的前后排真皮座椅、仪表板上部和前部、包括手套箱盖在内的仪表板下部、前后排中控台基本元件、方向盘安全气囊模组、前后车门饰件、车轮拱罩饰件<br>",
    interiorColorCockpitHexCode: "#4d3837",
    interiorColorCockpitStitchingCode: "#4d3837",
    interiorColorSeatColorHexCode: "#4d3837",
    interiorColorSeatStitchingColorHexCode: "#4d3837",
    interiorColorTagHexCode: "#782f2f",
    priceHistory: [
      {
        value: 1188000,
        currency: null,
        date: 1605135134,
      },
    ],
    priceValue: 1188000,
    mileageValue: 15140,
  },
  {
    id: 5486,
    dealerCode: 7000320,
    stockAge: 1107,
    vin: "WP0AA2986HS272073",
    lockForOrderId: null,
    inventoryNumber: "449513",
    stockStatus: "IN_STOCK",
    salesStatus: "AVAILABLE",
    vehicleType: "USED_CAR",
    vehicleOrigin: "TRADE_IN_FOR_USED_CAR",
    firstRegistrationDate: 1500393600,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: false,
    porscheApproved: false,
    modelName: "718 Cayman",
    modelCode: "982120",
    modelYear: 2017,
    exteriorColorHexCode: "#d9d9d6",
    exteriorColorTagHexCode: "#efefef",
    exteriorColorName: "细花白金属漆",
    interiorName: "黑色/波尔多红真皮组件，搭配部分真皮座椅",
    interiorDescription:
      "组件包括仪表组护盖、中控台主储物箱盖、座椅中心、座椅侧垫、座椅头枕、车门板扶手和车门拉手等处的真皮饰面。搭配双色调组合时，下列部件采用对比色：仪表组护盖、中控台主储物箱盖、座椅中心、车门板扶手和车门拉手",
    interiorColorCockpitHexCode: "#000000",
    interiorColorCockpitStitchingCode: "#000000",
    interiorColorSeatColorHexCode: "#782f2f",
    interiorColorSeatStitchingColorHexCode: "#782f2f",
    interiorColorTagHexCode: "#782f2f",
    priceHistory: [
      {
        value: 588000,
        currency: null,
        date: 1605901138,
      },
    ],
    priceValue: 588000,
    mileageValue: 46989,
  },
  {
    id: 4036,
    dealerCode: 7000320,
    stockAge: 1105,
    vin: "WP1AA29Y7LDA07898",
    lockForOrderId: null,
    inventoryNumber: "B30163",
    stockStatus: "IN_STOCK",
    salesStatus: "AVAILABLE",
    vehicleType: "USED_CAR",
    vehicleOrigin: "FACTORY_ORDER",
    firstRegistrationDate: 1591632000,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: false,
    porscheApproved: true,
    modelName: "Cayenne",
    modelCode: "9YAAA1",
    modelYear: 2020,
    exteriorColorHexCode: "#212721",
    exteriorColorTagHexCode: "#000000",
    exteriorColorName: "黑玉色金属漆",
    interiorName: "黑色内饰，部分真皮",
    interiorDescription:
      "下列部件采用与内饰同色的压花真皮：前后排座椅中心、前后排座椅侧垫、前后排座椅头枕中心、前后车门板扶手和门把手、前排中控台扶手和后排折叠扶手。光面真皮方向盘轮圈和选档杆。<br><br><br>",
    interiorColorCockpitHexCode: "#000000",
    interiorColorCockpitStitchingCode: "#000000",
    interiorColorSeatColorHexCode: "#000000",
    interiorColorSeatStitchingColorHexCode: "#000000",
    interiorColorTagHexCode: "#000000",
    priceHistory: [
      {
        value: 1028000,
        currency: null,
        date: 1604518097,
      },
    ],
    priceValue: 1028000,
    mileageValue: 6000,
  },
  {
    id: 5611,
    dealerCode: 7000320,
    stockAge: 1102,
    vin: "WP0AE2972KL123673",
    lockForOrderId: null,
    inventoryNumber: "A55732",
    stockStatus: "IN_STOCK",
    salesStatus: "AVAILABLE",
    vehicleType: "USED_CAR",
    vehicleOrigin: "TRADE_IN_FOR_USED_CAR",
    firstRegistrationDate: 1571846400,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: false,
    porscheApproved: true,
    modelName: "Panamera 4 E-Hybrid",
    modelCode: "97ABE1",
    modelYear: 2019,
    exteriorColorHexCode: "#474647",
    exteriorColorTagHexCode: "#ffcc00",
    exteriorColorName: "火山灰金属漆s",
    interiorName: "黑色/波尔多红双色调光面真皮内饰",
    interiorDescription:
      "黑色/波尔多红双色调真皮内饰组件 (所有真皮部件均采用光面真皮)。组件与标准颜色真皮内饰组件相同，装饰条采用对比色。仪表板上部和地毯采用较深的颜色。车顶衬里采用较深的颜色搭配黑色和波尔多红。仪表板上部和前后车门饰件上部的装饰性缝线采用较浅的颜色<br>",
    interiorColorCockpitHexCode: "#000000",
    interiorColorCockpitStitchingCode: "#782F2F",
    interiorColorSeatColorHexCode: "#782F2F",
    interiorColorSeatStitchingColorHexCode: "#782F2F",
    interiorColorTagHexCode: "#782f2f",
    priceHistory: [
      {
        value: 1288000,
        currency: null,
        date: 1605989213,
      },
    ],
    priceValue: 1288000,
    mileageValue: 7000,
  },
  {
    id: 4712,
    dealerCode: 7000320,
    stockAge: 1102,
    vin: "WP1AJ29YXKDA63431",
    lockForOrderId: null,
    inventoryNumber: "A62330",
    stockStatus: "IN_STOCK",
    salesStatus: "AVAILABLE",
    vehicleType: "USED_CAR",
    vehicleOrigin: "TRADE_IN_FOR_USED_CAR",
    firstRegistrationDate: 1563120000,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: false,
    porscheApproved: false,
    modelName: "Cayenne E-Hybrid",
    modelCode: "9YAAM1",
    modelYear: 2019,
    exteriorColorHexCode: "#3f2021",
    exteriorColorTagHexCode: "#85604e",
    exteriorColorName: "桃红木金属漆",
    interiorName: "黑色部分真皮内饰",
    interiorDescription:
      "标准颜色内饰，部分采用真皮材质。下列部件采用与内饰同色的压花真皮：前后排座椅中心、前后排座椅内侧垫、前后排座椅头枕中心、前后门板扶手和门把手、前排中控台扶手和折叠式后排扶手。光面真皮方向盘轮圈和选档杆<br>",
    interiorColorCockpitHexCode: "#000000",
    interiorColorCockpitStitchingCode: "#000000",
    interiorColorSeatColorHexCode: "#000000",
    interiorColorSeatStitchingColorHexCode: "#000000",
    interiorColorTagHexCode: "#000000",
    priceHistory: [
      {
        value: 938000,
        currency: null,
        date: 1605908211,
      },
    ],
    priceValue: 938000,
    mileageValue: 6960,
  },
  {
    id: 2800,
    dealerCode: 7000320,
    stockAge: 302,
    vin: "WP0AJ2974PL106697",
    lockForOrderId: 154,
    inventoryNumber: "C12345",
    stockStatus: "IN_USE",
    salesStatus: "RESERVED",
    vehicleType: "COMPANY_CAR",
    vehicleOrigin: "PURCHASE_FROM_WERKSWAGEN",
    firstRegistrationDate: 1664812800,
    licensePlate: null,
    interiorColorIsCustom: false,
    listingVisible: true,
    porscheApproved: false,
    modelName: "Panamera",
    modelCode: "97AAI1",
    modelYear: 2023,
    exteriorColorHexCode: "#eff5f9",
    exteriorColorTagHexCode: "#efefef",
    exteriorColorName: "细花白金属漆",
    interiorName: "黑色和波尔多红双色调真皮内饰，光面真皮",
    interiorDescription:
      "部分真皮内饰的所有部件均为光面真皮。此外：包括真皮座椅外侧侧垫在内的前后排真皮座椅、仪表板上部和前部、包括手套箱盖在内的仪表板下部、前后排中控台基本元件、前后车门饰件、车轮拱罩饰件。<br>车顶衬里、仪表板上部和车门内饰板、安全带、车门槛饰板、地毯和行李厢为黑色。仪表板上部和车门内饰板装饰性缝线为波尔多红。<br/>",
    interiorColorCockpitHexCode: "#000000",
    interiorColorCockpitStitchingCode: "#782F2F",
    interiorColorSeatColorHexCode: "#782F2F",
    interiorColorSeatStitchingColorHexCode: "#782F2F",
    interiorColorTagHexCode: "#782f2f",
    priceHistory: [
      {
        value: 870000,
        currency: null,
        date: 1673559511,
      },
    ],
    priceValue: 870000,
    mileageValue: 12000,
  },
];

function transformData(inputData) {
  return inputData.map((item) => ({
    modelCode: item.modelCode,
    modelName: item.modelName,
    modelYear: item.modelYear,
    stockStatusDescZh: "待售",
    priceValue: item.priceValue,
    vin: item.vin,
    stockAge: item.stockAge || 0,
  }));
}

console.log(transformData(data));
// export default data;
